baseurl = "https://www.ahoulette.com"
relativeurls = true
languageCode = "en-us"
title = "A blog analyzing stuff, using data"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-83439890-1"
disqusShortname = "datablog-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/houlad"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Adam_Houl"

[params]
    description = "A blog analyzing stuff, using data."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "kentucky.png"
    width = 50
    height = 50
    alt = "Logo"

    